name: workspace deployment

on:
  push:
    branches: [ workspace_publish ]

jobs:
  release:
    runs-on: windows-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Synapse Deployment
        uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: 'poductionenv'
          TemplateFile: './testingenvfabic/TemplateForWorkspace.json'
          ParametersFile: './testingenvfabic/TemplateForWorkspace_production.json'
          environment: 'Azure Public'
          resourceGroup: 'RGproduction'
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
          subscriptionId: ${{ secrets.subscriptionId }}
          tenantId: ${{ secrets.tenantId }}
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
          OverrideArmParameters: |
            {
              "Notebook 1_properties_bigDataPool_referenceName": { "value": "newpool" },
              "Notebook 2_properties_bigDataPool_referenceName": { "value": "newpool" },
              "Notebook 3_properties_bigDataPool_referenceName": { "value": "newpool" },
              "Notebook 16_properties_bigDataPool_referenceName": { "value": "newpool" },
              "Notebook 18_properties_bigDataPool_referenceName": { "value": "newpool" },
              "AzureKeyVault1_properties_typeProperties_baseUrl": { "value": "https://prodkeysynapse.vault.azure.net/" }
            }

